/* Auto-generated by scripts/embed-test-ca.sh from
 * tests/sidecars/tls/canboot-test.pem. Do not edit by hand;
 * regenerate via scripts/embed-test-ca.sh.
 */
#include <stddef.h>

const char canboot_test_ca_pem[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDgTCCAmmgAwIBAgIUIK7iPUlH1LnrW0KatbVN4Hev1kMwDQYJKoZIhvcNAQEL\n"
    "BQAwOzEVMBMGA1UEAwwMY2FuYm9vdC10ZXN0MRUwEwYDVQQKDAxDYW5Cb290IFRl\n"
    "c3QxCzAJBgNVBAYTAlpaMB4XDTI2MDUyMTIwMTMyOVoXDTM2MDUxODIwMTMyOVow\n"
    "OzEVMBMGA1UEAwwMY2FuYm9vdC10ZXN0MRUwEwYDVQQKDAxDYW5Cb290IFRlc3Qx\n"
    "CzAJBgNVBAYTAlpaMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvUZ/\n"
    "QG97KN9H9uIoVeXyTd/KXLukEj+MBtQgv+0Y4rdRZNJs4gdIOdID+Y3ZZuESQn1K\n"
    "mvMsIIe23uQVOAJzocjbA3UuzchzlR6jCdjXi/APNph7rD+fKTYdb4K7FXA3twq7\n"
    "A2PUGqDvuTBISKk1WcPCJpLcVd3lH8zyv2nNYYCvJsYAvF9ohwCd0WSSw6+K2GmH\n"
    "TLUbHw09+vADh/C10vGL8IVh8mRv2zlyn/jauskMpwsjpo4z058/UWC2Vs0EnicV\n"
    "ByKb51mfzd44GSWq7Tw07NDliLfNOmeCE3A23pxZDcwXj2Or43AoLZqXziHJ6MSN\n"
    "wxM5KjuJzXCEoMKGnwIDAQABo30wezAdBgNVHQ4EFgQU5LfHmSmRWTPMC5nzTpAk\n"
    "1xQXY+MwHwYDVR0jBBgwFoAU5LfHmSmRWTPMC5nzTpAk1xQXY+MwDwYDVR0TAQH/\n"
    "BAUwAwEB/zAoBgNVHREEITAfhwQKAAICggxjYW5ib290LXRlc3SCCWxvY2FsaG9z\n"
    "dDANBgkqhkiG9w0BAQsFAAOCAQEAIEJ2YeGhHXtsq4ud9dR3rgtgFOIW9Sa5MmxC\n"
    "wEEFRxy9AWmLTosokKM8y8ASeVqQT9f6lb1BQuKqLT4sG02Vpcq83PdWRx6q6tlg\n"
    "IklmC2kJswIS5tl0K7Jptv/eE2rSpyr/nkbia+L7CVn6kCJaP3hNJZMthDNIftuS\n"
    "0zeKEA9ROGGWozLj0RALw7KxkMKeLdtwe5Zp6cqM/WWOSd5nsKieNITtXPamV4yj\n"
    "qDmYNq1rf8dqEMP8RC6ai1XseQcxHFJup87dwWPi+VZog/ZQ+SHiU4EvPSAQ+mZ0\n"
    "l5p8oQuccIsoR+kxn7gQfQTxOcPzjNr/VJ0wsdQGW1HGut4wLQ==\n"
    "-----END CERTIFICATE-----\n"
;

const size_t canboot_test_ca_pem_len = sizeof(canboot_test_ca_pem);
