#!/usr/bin/env bash
# Regenerate tests/selftest/ca.c from tests/sidecars/tls/canboot-test.pem
# Run this whenever the test cert is rotated.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PEM="$ROOT/tests/sidecars/tls/canboot-test.pem"
OUT="$ROOT/tests/selftest/ca.c"

if [ ! -f "$PEM" ]; then
    echo "error: $PEM not found" >&2
    exit 1
fi

python3 - "$PEM" "$OUT" <<'PY'
import sys
pem = open(sys.argv[1]).read()
out = open(sys.argv[2], "w")
out.write("/* Auto-generated by tests/selftest/embed-test-ca.sh from\n")
out.write(" * tests/sidecars/tls/canboot-test.pem. Do not edit by hand;\n")
out.write(" * regenerate via tests/selftest/embed-test-ca.sh.\n */\n")
out.write("#include <stddef.h>\n\n")
out.write("const char canboot_test_ca_pem[] =\n")
for line in pem.splitlines():
    out.write('    "' + line + r'\n' + '"\n')
out.write(";\n\n")
out.write("const size_t canboot_test_ca_pem_len = sizeof(canboot_test_ca_pem);\n")
PY

echo "wrote $OUT"
